import libs = libkann%lib{kann}

import libs += libsfml%lib{sfml-all}
import libs += nlohmann-json%lib{json}


if ($cxx.target.class == 'linux')
  cc.coptions += -fopenmp
if ($cxx.target.class == 'windows')
  cc.coptions += -D_USE_MATH_DEFINES

exe{neuralevolution}: {hxx ixx txx cxx}{**} $libs testscript{**}
