import libs = libkann%lib{kann}

if ($cxx.target.class == 'linux')
  cc.coptions += -fopenmp
if ($cxx.target.class == 'windows')
  cc.coptions += -D_USE_MATH_DEFINES

exe{backpropagation}: {hxx ixx txx cxx}{**} $libs testscript{**}
